name: lunar_date
description: Arabic Lunar Calendar Pack for Dart Easily get lunar dates, convert and analyze.
version: 1.1.1
homepage: https://github.com/DarkCalendar/Lunar-History-Library-Dart

environment:
  sdk: ">=2.12.0 <3.0.0"